# Generated by Django 4.1.3 on 2022-12-05 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epic_chat_room', '0005_reply_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
